# Generated by Django 4.2.1 on 2023-05-06 15:25

from django.db import migrations, models
import utils.modules


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.modules.path_and_rename('products')),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
